### PR TITLE
Updating copyright year 2022

### PR DESCRIPTION
**Pull request by bbpgithubaudit**

### CODE REVIEW

**Comment by wvangeit** [comment]
@adrien-berchet can you have a look

**Comment by adrien-berchet** [comment]
> @adrien-berchet can you have a look

Sure!
I am wondering if we shouldn't also update the dates in the LICENCE.txt end COPYING-BSD files?

**Comment by wvangeit** [comment]
Good point about the license files. @alex4200 what do you think?

**Comment by alex4200** [comment]
Yes I agree. The other two files should have been also updated, but I need to fix my regex. 

Please close this MR, I created a new MR: https://github.com/BlueBrain/TMD/pull/51

**Pull request closed without merging**
