### PR TITLE
remove enum compat

### PR DESCRIPTION
**Pull request by arnaudon**
This dependency is not needed apparently, and break spack (@GianlucaFicarelli )

### CODE REVIEW

**Comment by GianlucaFicarelli** [comment]
I see that tests fails in https://github.com/BlueBrain/TMD/pull/40/checks?check_run_id=2123032582
because 
```
  morphio._morphio.RawDataError: Error in HDF5 Group
  h5v2 is no longer supported, see: https://github.com/BlueBrain/MorphIO#H5v2
```
I think this is related to the removal of the h5v2 support that @wizmer mentioned?

**Comment by arnaudon** [comment]
Yes, I'm on it, same for TNS

**Comment by arnaudon** [comment]
Here you are, can you merge?

**Review by GianlucaFicarelli — APPROVED** [review]
Great! Approving even though I don't know if my approval is enough.

**Comment by GianlucaFicarelli** [comment]
It looks my approval is not enough, and I don't have the permission to merge either.

**Comment by arnaudon** [comment]
@eleftherioszisis , can you merge things here?

**Review by adrien-berchet — APPROVED** [review]

**Pull request merged**
